import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {importTs} from './transpile-import.mjs';
const e=await importTs('lib/microgame/engine.ts');
const s=await importTs('lib/microgame/skill-engine.ts');
const model=await importTs('lib/microgame/skill-model.ts');
const m=fs.existsSync('lib/microgame/match-engine.ts')?await importTs('lib/microgame/match-engine.ts'):null;
function api(){assert.ok(m,'normal match engine must exist');return m;}
function lobby(n=2){let r=e.createMicrogameRoom({code:'MCR22',hostUid:'p1',nickname:'Ada',now:100});for(let i=2;i<=n;i++)r=e.joinMicrogamePlayer(r,{uid:`p${i}`,nickname:`Player ${i}`,now:100+i});return r;}
function start(n=2,at=1000){return api().startMicrogameMatch(lobby(n),'p1',0,at);}
function positions(r){return Object.fromEntries(Object.keys(r.players).map((uid,i)=>[uid,{uid,roundNumber:r.roundNumber,x:i===0?50:80,y:i===0?50:80,updatedAt:r.round.endsAt-50}]));}
function finish(r,uid='p2'){return api().settleMicrogameMatchRound(r,uid,r.roundNumber,positions(r),api().matchSettleAt(r)+1);}
function advance(r,uid='p2'){return api().advanceMicrogameMatch(r,uid,r.roundNumber,r.match.nextAt);}
function complete(r){for(let i=0;i<8;i++){r=finish(r);if(i<7)r=advance(r);}return r;}

test('fresh lobby supports a normal match without changing legacy test rounds',()=>{let r=start();assert.equal(r.status,'playing');assert.equal(r.match.status,'active');assert.equal(r.match.order.length,8);assert.equal(new Set(r.match.order).size,8);assert.equal(r.activeGameId,r.match.order[0]);assert.deepEqual(e.normalizeMicrogameState(r),r);assert.equal(e.startBombPassTest(lobby(),'p1',1000).activeGameId,'bomb-pass');});
test('only host starts and 2–6 players are required',()=>{api();assert.throws(()=>m.startMicrogameMatch(lobby(),'p2',0,1000));assert.throws(()=>m.startMicrogameMatch(lobby(1),'p1',0,1000));let r=lobby(6);r.players.p7={uid:'p7',nickname:'P7',seat:6,score:0};assert.throws(()=>m.startMicrogameMatch(r,'p1',0,1000));assert.equal(Object.keys(start(6).players).length,6);});
test('shuffle is deterministic per start command, variable across new matches and includes all nine games over many matches',()=>{api();assert.deepEqual(start(),start());const orders=new Set(),all=new Set();for(let i=0;i<100;i++){const r=start(2,1000+i*31);assert.equal(new Set(r.match.order).size,8);r.match.order.forEach(id=>all.add(id));orders.add(r.match.order.join(','));}assert.equal(all.size,9);assert.ok(orders.size>50);});
test('start clears old test scores but never rewinds the network round number',()=>{let r=lobby();r.players.p1.score=1500;r.roundNumber=42;r=api().startMicrogameMatch(r,'p1',42,1000);assert.equal(r.roundNumber,43);assert.equal(r.players.p1.score,0);assert.equal(r.match.baseRoundNumber,42);});
test('duplicate and stale start commands cannot reset an active match',()=>{let r=start();assert.deepEqual(m.startMicrogameMatch(r,'p1',0,1000),r);assert.throws(()=>m.startMicrogameMatch(r,'p1',r.roundNumber,1001),/maç|tur/i);});
test('settlement records each score once, and duplicate callbacks do not change nextAt',()=>{let r=finish(start());assert.equal(r.status,'results');assert.equal(r.match.index,0);assert.equal(Object.keys(r.match.history).length,1);assert.equal(r.match.nextAt,r.updatedAt+m.INTERMISSION_MS);const twice=m.settleMicrogameMatchRound(r,'p1',r.roundNumber,positions(r),r.updatedAt+2000);assert.deepEqual(twice,r);const recap=r.match.history['0'];for(const p of Object.values(r.players)){assert.equal(recap.totals[p.uid],p.score);assert.equal(recap.gains[p.uid],p.score);assert.ok(p.score>=0&&p.score<=100);}});
test('settlement never accepts nonmembers, early deadlines, nonfinite time or wrong round',()=>{let r=start();assert.throws(()=>m.settleMicrogameMatchRound(r,'outsider',r.roundNumber,{},m.matchSettleAt(r)));assert.throws(()=>m.settleMicrogameMatchRound(r,'p1',r.roundNumber,{},r.round.startsAt));assert.throws(()=>m.settleMicrogameMatchRound(r,'p1',r.roundNumber,{},NaN));assert.deepEqual(m.settleMicrogameMatchRound(r,'p1',r.roundNumber-1,{},m.matchSettleAt(r)),r);});
test('all connected members can advance after intermission, including without host',()=>{let r=finish(start(6));assert.deepEqual(m.advanceMicrogameMatch(r,'p3',r.roundNumber,r.match.nextAt-1),r);let next=m.advanceMicrogameMatch(r,'p3',r.roundNumber,r.match.nextAt);assert.equal(next.match.index,1);assert.equal(next.roundNumber,r.roundNumber+1);assert.equal(next.activeGameId,r.match.order[1]);assert.equal(next.status,'playing');assert.deepEqual(m.advanceMicrogameMatch(next,'p2',r.roundNumber,r.match.nextAt),next);});
test('background return starts only one new round with a full instruction period',()=>{let r=finish(start());const now=r.match.nextAt+60000;r=m.advanceMicrogameMatch(r,'p2',r.roundNumber,now);assert.equal(r.match.index,1);assert.ok(r.round.instructionsUntil>=now+3000);assert.ok(r.round.startsAt>now+6000);});
test('round summaries survive Firebase array-shaped order/history and missing empty maps',()=>{let r=finish(start());const raw=structuredClone(r);raw.match.order=Object.fromEntries(raw.match.order.map((id,i)=>[i,id]));raw.match.history=Object.assign([],{0:raw.match.history['0']});assert.deepEqual(e.normalizeMicrogameState(raw),r);r=start();delete r.match.history;assert.deepEqual(e.normalizeMicrogameState(r).match.history,{});});
test('complete eight-round match has no repeats, no elimination and a stable final',()=>{for(const n of [2,4,6]){let r=start(n);const ids=[];for(let i=0;i<8;i++){ids.push(r.activeGameId);r=finish(r);if(i<7)r=advance(r);}assert.equal(new Set(ids).size,8);assert.equal(r.match.status,'finished');assert.equal(r.match.index,7);assert.equal(r.match.nextAt,0);assert.equal(Object.keys(r.match.history).length,8);assert.equal(Object.keys(r.players).length,n);assert.deepEqual(m.advanceMicrogameMatch(r,'p2',r.roundNumber,r.updatedAt+1e5),r);for(const p of Object.values(r.players))assert.ok(p.score>=0&&p.score<=800);}});
test('rematch resets totals/history, keeps room and roster, increments global round id',()=>{const old=complete(start(4));let r=m.startMicrogameMatch(old,'p1',old.roundNumber,old.updatedAt+1000);assert.equal(r.code,old.code);assert.notEqual(r.match.id,old.match.id);assert.equal(r.roundNumber,old.roundNumber+1);assert.equal(r.match.index,0);assert.deepEqual(r.match.history,{});assert.ok(Object.values(r.players).every(p=>p.score===0));assert.deepEqual(m.settleMicrogameMatchRound(r,'p2',old.roundNumber,{},r.round.endsAt),r);});
test('new members cannot enter midmatch, existing members can reconnect',()=>{const r=start();assert.throws(()=>e.joinMicrogamePlayer(r,{uid:'new',nickname:'New'}));assert.deepEqual(e.joinMicrogamePlayer(r,{uid:'p2',nickname:'Same'}),r);});
test('lobby reset cannot interrupt an active match and only host can reset completed match',()=>{const r=start();assert.throws(()=>api().openMicrogameLobby(r,'p1',r.roundNumber,1001));const done=complete(r);assert.throws(()=>m.openMicrogameLobby(done,'p2',done.roundNumber,done.updatedAt+1));const reset=m.openMicrogameLobby(done,'p1',done.roundNumber,done.updatedAt+1);assert.equal(reset.status,'lobby');assert.equal(reset.match,null);assert.equal(reset.roundNumber,done.roundNumber);assert.ok(Object.values(reset.players).every(p=>p.score===0));});
test('shared ranking uses competition ranks and keeps exact ties rather than choosing by nickname',()=>{const r=lobby(4);r.players.p1.score=80;r.players.p2.score=80;r.players.p3.score=30;r.players.p4.score=0;const ranks=api().microgameStandings(r);assert.deepEqual(ranks.map(p=>p.rank),[1,1,3,4]);assert.deepEqual(ranks.filter(p=>p.rank===1).map(p=>p.uid),['p1','p2']);});
test('same game in a rematch uses a fresh monotonic round number',()=>{let r=complete(start());const oldRound=r.roundNumber;r=m.startMicrogameMatch(r,'p1',oldRound,r.updatedAt+100);assert.ok(r.roundNumber>oldRound);assert.equal(r.match.baseRoundNumber,oldRound);});
test('100 deterministic full matches survive retries, reconnect snapshots and cumulative point bookkeeping',()=>{api();for(let seed=0;seed<100;seed++){let r=start(2+seed%5,1000+seed*77),sums=Object.fromEntries(Object.keys(r.players).map(uid=>[uid,0]));for(let i=0;i<8;i++){r=finish(e.normalizeMicrogameState(JSON.parse(JSON.stringify(r))));const recap=r.match.history[String(i)];for(const p of Object.values(r.players)){sums[p.uid]+=recap.gains[p.uid];assert.equal(sums[p.uid],p.score);}assert.deepEqual(finish(r),r);if(i<7)r=advance(r);}assert.equal(r.match.status,'finished');}});
test('every existing settlement participates in the real match loop',()=>{api();const seen=new Set();for(let seed=0;seed<12;seed++){let r=start(2,1000+seed);for(let i=0;i<8;i++){seen.add(r.activeGameId);r=finish(r);if(i<7)r=advance(r);}}assert.equal(seen.size,9);});
