import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {importTs} from './transpile-import.mjs';
const engine=await importTs('lib/microgame/engine.ts');
const {MICROGAMES}=await importTs('lib/microgame/registry.ts');
const present=fs.existsSync('lib/microgame/skill-engine.ts');
const skill=present?await importTs('lib/microgame/skill-engine.ts'):null;
const model=present?await importTs('lib/microgame/skill-model.ts'):null;
const ids=['freeze-dance','echo-gestures','memory-spot','red-light','shadow-match','hold-release','crown-control'];
function room(n=2){let r=engine.createMicrogameRoom({code:'MCR22',hostUid:'p1',nickname:'Ada',now:100});for(let i=2;i<=n;i++)r=engine.joinMicrogamePlayer(r,{uid:`p${i}`,nickname:`P${i}`,now:101+i});return r;}
function start(id,n=2){assert.ok(skill,'skill engine must exist');return skill.startSkillTest(room(n),'p1',id,1000);}
function finish(r){return skill.settleSkillRound(r,'p1',r.roundNumber,r.round.endsAt+2300);}
test('registry contains all nine chosen games exactly once',()=>{assert.deepEqual(MICROGAMES.map(x=>x.id),['bomb-pass','shrink-arena',...ids]);});
for(const id of ids){
 test(`${id}: host starts for 2 and 6 players, serializes, and blocks mid-round restarts`,()=>{for(const n of [2,6]){let r=start(id,n);assert.equal(r.round.gameId,id);assert.ok(r.round.instructionsUntil<r.round.startsAt);assert.ok(r.round.endsAt>r.round.startsAt);assert.equal(r.activeGameId,id);assert.deepEqual(engine.normalizeMicrogameState(JSON.parse(JSON.stringify(r))),r);assert.throws(()=>skill.startSkillTest(r,'p1',id,1100),/tur/i);}assert.throws(()=>skill.startSkillTest(room(),'p2',id,1000),/sahibi/);});
}
test('same round timestamp produces identical puzzles across transaction retries',()=>{assert.deepEqual(start('echo-gestures'),start('echo-gestures'));});
test('unknown games and a one-player start are rejected',()=>{assert.ok(skill);assert.throws(()=>skill.startSkillTest(room(),'p1','bad',1000));assert.throws(()=>skill.startSkillTest(room(1),'p1','freeze-dance',1000),/2/);});
test('Firebase omission of empty submissions is normalized',()=>{let r=start('memory-spot');delete r.round.submissions;assert.deepEqual(engine.normalizeMicrogameState(r).round.submissions,{});});
test('memory: exact hit beats far hit; no scoring before reveal or repeated guesses',()=>{let r=start('memory-spot');const spec=model.memorySpec(r.round);const at=r.round.startsAt+2300;assert.throws(()=>skill.submitSkillEvidence(r,'p1',r.roundNumber,{kind:'spot',x:spec.target.x,y:spec.target.y,at:r.round.startsAt+100},at),/gösterim/i);r=skill.submitSkillEvidence(r,'p1',r.roundNumber,{kind:'spot',x:spec.target.x,y:spec.target.y,at},at+30);const once=JSON.stringify(r);assert.equal(JSON.stringify(skill.submitSkillEvidence(r,'p1',r.roundNumber,{kind:'spot',x:0,y:0,at:at+100},at+110)),once);r=skill.submitSkillEvidence(r,'p2',r.roundNumber,{kind:'spot',x:0,y:0,at},at+30);r=finish(r);assert.equal(r.players.p1.score,100);assert.ok(r.players.p2.score<r.players.p1.score);});
test('shadow: correct silhouette scores, wrong silhouette does not',()=>{let r=start('shadow-match');const spec=model.shadowSpec(r.round);const at=r.round.startsAt+2000;r=skill.submitSkillEvidence(r,'p1',r.roundNumber,{kind:'choice',choice:spec.target,at},at+1);r=skill.submitSkillEvidence(r,'p2',r.roundNumber,{kind:'choice',choice:spec.choices.find(x=>x!==spec.target),at},at+1);r=finish(r);assert.ok(r.players.p1.score>=70);assert.equal(r.players.p2.score,0);});
test('gesture classifier supports tap, hold and four swipe directions; cancel never passes',()=>{assert.ok(model);for(const [dx,dy,duration,expected] of [[0,0,100,'tap'],[0,0,650,'hold'],[40,0,200,'right'],[-40,0,200,'left'],[0,-40,200,'up'],[0,40,200,'down'],[0,0,350,null]])assert.equal(model.classifyGesture({dx,dy,duration,cancelled:false}),expected);assert.equal(model.classifyGesture({dx:0,dy:0,duration:900,cancelled:true}),null);});
test('gestures: full correct sequence beats empty input, but cannot start during demo',()=>{let r=start('echo-gestures');const sequence=model.gestureSequence(r.round);let at=r.round.startsAt+model.GESTURE_PREVIEW_MS+800;const gestures=sequence.map(g=>{const duration=g==='hold'?650:150;const a={dx:g==='left'?-45:g==='right'?45:0,dy:g==='up'?-45:g==='down'?45:0,duration,at,cancelled:false};at+=900;return a;});r=skill.submitSkillEvidence(r,'p1',r.roundNumber,{kind:'gestures',gestures},at);r=finish(r);assert.ok(r.players.p1.score>=70);assert.equal(r.players.p2.score,0);});
test('hold: release at real cue scores, early/cancelled release scores zero',()=>{for(const mode of ['early','cancel','correct']){let r=start('hold-release');const cue=model.releaseAt(r.round);const upAt=mode==='early'?cue-100:cue+250;r=skill.submitSkillEvidence(r,'p1',r.roundNumber,{kind:'release',downAt:r.round.startsAt-500,upAt,cancelled:mode==='cancel'},upAt+10);r=finish(r);assert.equal(r.players.p1.score>0,mode==='correct');}});
test('hold: arming after the reveal cannot gain points',()=>{let r=start('hold-release'),cue=model.releaseAt(r.round);r=skill.submitSkillEvidence(r,'p1',r.roundNumber,{kind:'release',downAt:cue,upAt:cue+100,cancelled:false},cue+200);assert.equal(finish(r).players.p1.score,0);});
test('freeze: doing nothing gives no points; moving only in move phases scores',()=>{let r=start('freeze-dance');let x=25;const samples=[];for(let t=r.round.startsAt;t<=r.round.endsAt;t+=80){const signal=model.signalAt(r.round,t);if(signal.go)x+=(Math.floor((t-r.round.startsAt)/80)%16<8?1:-1)*2;samples.push({x,y:50,at:t});}r=skill.submitSkillEvidence(r,'p1',r.roundNumber,{kind:'trace',samples},r.round.endsAt+100);r=finish(r);assert.ok(r.players.p1.score>30,JSON.stringify(r.round.submissions));assert.equal(r.players.p2.score,0);});
test('red light: releasing in red beats holding throughout; stopping is replayed deterministically',()=>{let r=start('red-light');const changes=[];let previous=false;for(let t=r.round.startsAt;t<=r.round.endsAt;t+=20){let held=model.signalAt(r.round,t).go;if(held!==previous){changes.push({at:t,held});previous=held;}}const smart=model.raceState(r.round,changes,r.round.endsAt);const reckless=model.raceState(r.round,[{at:r.round.startsAt,held:true}],r.round.endsAt);assert.ok(smart.progress>reckless.progress);assert.equal(smart.penalties,0);r=skill.submitSkillEvidence(r,'p1',r.roundNumber,{kind:'run',changes},r.round.endsAt+50);assert.ok(finish(r).players.p1.score>0);});
test('crown: final fresh center holder wins on a shared snapshot; stale clients do not win',()=>{let r=start('crown-control');const positions={p1:{uid:'p1',roundNumber:r.roundNumber,x:50,y:50,updatedAt:r.round.endsAt-90},p2:{uid:'p2',roundNumber:r.roundNumber,x:80,y:80,updatedAt:r.round.endsAt-50}};r=skill.settleCrownRound(r,'p2',r.roundNumber,positions,r.round.endsAt+2300);assert.equal(r.players.p1.score,100);assert.ok(r.players.p2.score<100);assert.deepEqual(skill.settleCrownRound(r,'p1',r.roundNumber,positions,r.round.endsAt+2400),r);let fresh=start('crown-control');positions.p1.updatedAt=fresh.round.startsAt;fresh=skill.settleCrownRound(fresh,'p1',fresh.roundNumber,positions,fresh.round.endsAt+2300);assert.equal(fresh.players.p1.score,0);});
test('late, nonmember, wrong-round, wrong-game, malformed or future evidence is rejected',()=>{let r=start('memory-spot');const e={kind:'spot',x:50,y:50,at:r.round.startsAt+2300};assert.throws(()=>skill.submitSkillEvidence(r,'outsider',r.roundNumber,e,e.at+1));assert.throws(()=>skill.submitSkillEvidence(r,'p1',r.roundNumber-1,e,e.at+1),/tur/i);assert.throws(()=>skill.submitSkillEvidence(r,'p1',r.roundNumber,{...e,x:Infinity},e.at+1));assert.throws(()=>skill.submitSkillEvidence(r,'p1',r.roundNumber,{...e,x:101},e.at+1));assert.throws(()=>skill.submitSkillEvidence(r,'p1',r.roundNumber,e,e.at-200));assert.throws(()=>skill.submitSkillEvidence(r,'p1',r.roundNumber,e,r.round.endsAt+3000));assert.throws(()=>skill.submitSkillEvidence(r,'p1',r.roundNumber,{kind:'choice',choice:'cat',at:e.at},e.at+1));});
test('settle waits for submission grace, missing input zero, applies scores once and keeps all players',()=>{let r=start('memory-spot',6);assert.throws(()=>skill.settleSkillRound(r,'p1',r.roundNumber,r.round.endsAt),/bekleniyor/i);r=finish(r);const twice=finish(r);assert.deepEqual(twice,r);assert.equal(Object.keys(r.players).length,6);assert.equal(Object.values(r.players).reduce((s,p)=>s+p.score,0),0);const next=skill.startSkillTest(r,'p1','shadow-match',r.updatedAt+1);assert.equal(next.roundNumber,2);assert.throws(()=>skill.submitSkillEvidence(next,'p1',1,{kind:'choice',choice:'cat',at:next.round.startsAt+2000},next.round.startsAt+2100),/tur/i);});
