import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {importTs} from './transpile-import.mjs';
const e=await importTs('lib/microgame/engine.ts'),m=await importTs('lib/microgame/match-engine.ts');
const rule=JSON.parse(fs.readFileSync('firebase/database.rules.json','utf8')).rules.microgameRooms.$code.match;
class Snapshot{constructor(root,path=[]){this.root=root;this.path=path;}val(){let node=this.root;for(const p of this.path)node=node?.[p];return node??null;}child(key){assert.equal(typeof key,'string','RuleDataSnapshot.child expects a string path');return new Snapshot(this.root,[...this.path,...String(key).split('/')]);}parent(){return new Snapshot(this.root,this.path.slice(0,-1));}exists(){return this.val()!==null;}hasChildren(keys){return keys.every(k=>this.child(k).exists());}isNumber(){return typeof this.val()==='number'&&Number.isFinite(this.val());}isString(){return typeof this.val()==='string';}}
function validate(expression,r,old=null,uid='p1',subpath=[]){assert.ok(expression,'match rules must be present');const root={microgameRooms:{MCR22:r}},data={microgameRooms:{MCR22:old}};return Function('newData','data','root','auth','$code','$uid','$other',`return (${expression});`)(new Snapshot(root,['microgameRooms','MCR22','match',...subpath]),new Snapshot(data,['microgameRooms','MCR22','match',...subpath]),new Snapshot(data),{uid},'MCR22',subpath.at(-1),subpath.at(-1));}
function start(){let r=e.createMicrogameRoom({code:'MCR22',hostUid:'p1',nickname:'A',now:10});r=e.joinMicrogamePlayer(r,{uid:'p2',nickname:'B',now:20});return m.startMicrogameMatch(r,'p1',0,1000);}
test('match schema accepts complete eight-round lifecycle and replay',()=>{let r=start();assert.equal(validate(rule?.['.validate'],r),true);assert.equal(validate(rule.order['.validate'],r,null,'p1',['order']),true);for(let i=0;i<8;i++){let old=r;r=m.settleMicrogameMatchRound(r,'p2',r.roundNumber,{},m.matchSettleAt(r)+1);assert.equal(validate(rule['.validate'],r,old,'p2'),true);if(i<7){old=r;r=m.advanceMicrogameMatch(r,'p2',r.roundNumber,r.match.nextAt);assert.equal(validate(rule['.validate'],r,old,'p2'),true);}}const old=r;r=m.startMicrogameMatch(r,'p1',r.roundNumber,r.updatedAt+1);assert.equal(validate(rule['.validate'],r,old),true);});
test('nonhost cannot initialize or replace a match while members may progress',()=>{let r=start();assert.equal(validate(rule?.['.validate'],r,null,'p2'),false);});
test('match schema rejects invalid count, duplicate games, unknown game, index and status drift',()=>{assert.ok(rule);for(const change of [r=>r.match.index=9,r=>r.match.status='test',r=>r.match.baseRoundNumber=-1,r=>r.roundNumber=12,r=>r.activeGameId='invalid',r=>r.match.status='finished']){const r=start();change(r);assert.equal(validate(rule['.validate'],r),false);}for(const change of [r=>r.match.order[1]=r.match.order[0],r=>r.match.order[2]='invalid',r=>r.match.order.pop()]){const r=start();change(r);assert.equal(validate(rule.order['.validate'],r,null,'p1',['order']),false);}assert.equal(rule.order.$other['.validate'],false);});
test('new match config cannot change during existing match, and nextAt cannot be negative',()=>{assert.ok(rule);const old=start();for(const change of [r=>r.match.order.reverse(),r=>r.match.startedAt++,r=>r.match.baseRoundNumber++,r=>r.match.nextAt=-1]){const r=structuredClone(old);change(r);assert.equal(validate(rule['.validate'],r,old,'p2'),false);}});
