import { canonicalCharacter } from "./character-catalog";
import type { CharacterSeed } from "./types";

export type CharacterProfile = { role: string; description: string; strengths: readonly [string, string]; weakness: string };
// These are authored game interpretations, NOT objective power rankings or canonical biographies.
const ROLES = {
  strategist: {role:"Stratejist", strengths:["Uzun vadeli plan","Fırsatları okuma"],weakness:"Plan bozulduğunda esnemesi gerekebilir."},
  leader: {role:"Lider",strengths:["İnsanları toplama","Karar alma"],weakness:"Otorite çatışması ekip uyumunu zorlayabilir."},
  diplomat: {role:"Diplomat",strengths:["İkna","İlişki yönetimi"],weakness:"Her çatışma konuşarak çözülmeyebilir."},
  protector: {role:"Koruyucu",strengths:["Krizde inisiyatif","Ekibi savunma"],weakness:"Sert yaklaşımı hassas işleri zorlaştırabilir."},
  connector: {role:"Bağlantı kurucu",strengths:["Bilgi akışı","Sosyal çevre"],weakness:"Çok fazla ilişki, sır tutmayı zorlaştırabilir."},
  healer: {role:"İyileştirici",strengths:["İnsanlara destek","Sorun çözme"],weakness:"Kaynak ve güvenli çalışma ortamına ihtiyaç duyar."},
  artist: {role:"Yaratıcı",strengths:["Farklı bakış","Doğaçlama"],weakness:"Katı kurallı işlerde desteğe ihtiyaç duyabilir."},
  merchant: {role:"Pazarlıkçı",strengths:["Kaynak yönetimi","Alışveriş zekâsı"],weakness:"Kendi çıkarı ile ekip yararı çatışabilir."},
  observer: {role:"Gözlemci",strengths:["Ayrıntıları fark etme","Sabırlı takip"],weakness:"Hızlı karar gereken anları kaçırabilir."},
  rebel: {role:"Atılgan",strengths:["Cesaret","Beklenmedik hamle"],weakness:"Acele kararlar gereksiz risk yaratabilir."},
  maker: {role:"Üretici",strengths:["Pratik çözüm","Teknik düşünme"],weakness:"Çözüm üretmek için zaman ve malzeme gerekir."},
} as const;
type Role = keyof typeof ROLES;
const PROFILES: Record<string, [Role, string]> = {
  "Hatice Sultan":["diplomat","Saray ilişkilerinin merkezine duygusal sezgi ve yakın bağlar getirir."],
  "Ayşe Hafsa Sultan":["leader","Sarayın iç düzenini bir arada tutacak deneyimli bir otorite olarak düşünülebilir."],
  "Mimar Sinan":["maker","Kadroda tasarım, yapı kurma ve uzun vadeli çözüm geliştirme rolüne aday."],
  "Aybige Hatun":["rebel","Kuralları sorgulayan, hareketli görevlerde inisiyatif alabilecek bir tercih."],
  "Gül Ağa":["connector","Sarayın günlük işlerinde haber ve insan bağlantılarını canlı tutacak bir rol."],
  "Ebu Suud Efendi":["observer","Kuralları ve kararların sonuçlarını tartışacak bir danışman rolüne aday."],
  "Taşlıcalı Yahya":["artist","Söz ve cesaret gerektiren görevlerde yaratıcı bir destek olarak düşünülebilir."],
  "Şehzade Cihangir":["observer","İnsanları anlamaya ve ayrıntıları izlemeye dayalı görevlerde değerlendirilebilir."],
  "Firuze":["diplomat","Dikkat çekme ve ilişkilerin yönünü değiştirme üzerine kurulacak bir oyun tercihi."],
  "Fatma Sultan":["strategist","Saray içi dengeleri okuyarak rakip planlara karşı hamle üretme rolüne aday."],
  "Victoria":["observer","Gizlilik ve hedefe odaklı takip gereken görevlerde düşünülebilir."],
  "Malkoçoğlu Bali Bey":["protector","Sahayı kontrol etme ve tehlikeli görevlerde ekibi koruma rolüne aday."],
  "Prenses İsabella":["diplomat","Farklı çevrelerle ilişki kurma ve diplomasi gerektiren bir kadroya renk katar."],
  "Yakup Efendi":["healer","Sağlık ve hazırlık odaklı görevlerde destek rolünde düşünülebilir."],
  "Şehzade Mehmet":["leader","Sorumluluk ve liderlik potansiyeli üzerine kurulacak bir kadro tercihi."],
  "Hürrem Sultan":["strategist","Saray dengelerinde ittifak ve uzun vadeli hamle kurma fikriyle öne çıkar."],
  "Kanuni Sultan Süleyman":["leader","Güçlü otorite ve büyük kararlar gerektiren bir ekibin merkezine aday."],
  "İbrahim Paşa":["strategist","Yönetim ve diplomasi arasında geniş bir görev alanı üstlenebilir."],
  "Rüstem Paşa":["merchant","Kaynak, hesap ve pazarlık gerektiren görevlerde stratejik bir tercih."],
  "Sümbül Ağa":["connector","İnsanları organize edip bilginin doğru kişiye ulaşmasını sağlayan rol için düşün."],
  "Nigar Kalfa":["connector","Günlük operasyonları ve insan ilişkilerini birlikte yürütecek rol için düşün."],
  "Matrakçı Nasuh":["maker","Yaratıcılık ile pratik becerileri birleştiren çok yönlü destek rolüne aday."],
  "Mahidevran Sultan":["protector","Kendi tarafını koruma ve kararlı biçimde savunma rolüyle değerlendirilebilir."],
  "Mihrimah Sultan":["diplomat","İlişkiler ve nüfuz üzerinden sonuç alma gerektiren görevlerde düşünülebilir."],
  "Şehzade Mustafa":["leader","Çevresinde güven ve dayanışma toplama üzerine kurulacak bir tercih."],
  "Polat Alemdar":["strategist","Gizli plan, saha koordinasyonu ve kontrollü hamle gerektiren görevler için düşün."],
  "Memati Baş":["protector","Tehlike karşısında hızlı harekete geçen, saha odaklı bir destek rolüne aday."],
  "Süleyman Çakır":["leader","Çevresini harekete geçirme ve riskli işlerin sorumluluğunu alma rolüne aday."],
  "Abdülhey Çoban":["protector","Arka planda güvenilir saha desteği ve takip rolünde değerlendirilebilir."],
  "Laz Ziya":["merchant","Güç ve kaynak ilişkileri üzerinden pazarlık yürütme rolü için düşün."],
  "Aslan Akbey":["strategist","Bilgi toplama ve çok adımlı operasyon planlama rolüne aday."],
  "Elif Eylül":["diplomat","Kuralları, insanları ve farklı tarafların çıkarlarını uzlaştırma rolü için düşün."],
  "Pala":["protector","Doğrudan ve sert çözümlerin gerektiği görevlerde riskli bir saha tercihi."],
  "Ramiz Dayı":["strategist","Deneyim, sabır ve uzun vadeli düşünme üzerine kurulacak bir mentor tercihi."],
  "Ezel Bayraktar":["strategist","Karşı tarafı okuma ve sabırlı plan yürütme rolünde değerlendirilebilir."],
  "Eyşan Tezcan":["diplomat","İkna ve ilişkilerin yönünü değiştirme gerektiren görevlerde düşünülebilir."],
  "Cengiz Atay":["merchant","Fırsatları paraya veya konuma çevirme rolünde güçlü ama riskli bir tercih."],
  "Ali Kırgız":["protector","Sadakat ve doğrudan harekete geçme gerektiren görevler için düşün."],
  "Kenan Birkan":["leader","Güç ve nüfuzla alan açan, karşılığında uyum isteyen bir kadro tercihi."],
  "Bihter Ziyagil":["diplomat","Duygusal gerilim ve sosyal ilişkiler içeren görevlerde etkili bir rol alabilir."],
  "Behlül Haznedar":["diplomat","Sosyal ortama uyum ve dikkat çekme gerektiren görevlerde değerlendirilebilir."],
  "Firdevs Yöreoğlu":["strategist","Sosyal fırsatları önceden okuyup konum kazanma rolüne aday."],
  "Adnan Ziyagil":["leader","Kaynak ve düzen sağlayan, sakin yönetim rolü için düşünülebilir."],
  "Nihal Ziyagil":["observer","Duygusal ayrıntıları ve yakın ilişkileri izleme rolüyle değerlendirilebilir."],
  "Beşir":["observer","Arka planda olanları fark etme ve sessiz destek rolü için düşün."],
  "Erdal Bakkal":["merchant","Günlük alışveriş ve küçük kaynakları değerlendirme işlerinde düşünülebilir."],
  "İsmail Abi":["connector","Moral ve dayanışma isteyen bir ekibe sosyal destek olarak katılabilir."],
  "Mecnun Çınar":["artist","Alışılmış çözümler işlemediğinde beklenmedik fikirler çıkarabilecek bir tercih."],
  "Leyla":["diplomat","İnsan ilişkileri ve duygusal denge odaklı bir rol için düşünülebilir."],
  "Yavuz":["rebel","Kuralların dışında pratik yol bulma gerektiren görevlerde düşünülebilir."],
  "Ak Sakallı Dede":["observer","Ekibe farklı bir perspektif sunan yol gösterici rolü için düşün."],
  "Burhan Altıntop":["connector","Sosyal ortamın dikkatini üzerine çekme ve kendini gösterme rolüne aday."],
  "Aslı Sütçüoğlu":["diplomat","Gündelik sorunları ve farklı kişilikleri uzlaştırma rolünde değerlendirilebilir."],
  "Volkan Sütçüoğlu":["artist","Eğlence ve doğaçlama isteyen işlerde yaratıcı bir tercih."],
  "Şahika Koçarslanlı":["merchant","Kaynak ve konum avantajını sahaya taşıyan bir pazarlık rolüne aday."],
  "Gaffur Aksoy":["maker","Gündelik işleri yürütme ve pratik çözümler bulma rolüne aday."],
  "Tahsin Sütçüoğlu":["leader","Alışılmış düzeni koruyan, deneyime dayalı yönetim rolü için düşün."],
  "Yamaç Koçovalı":["strategist","Kriz anında plan ve saha hareketini birleştiren rol için düşünülebilir."],
  "İdris Koçovalı":["leader","Topluluğu bir arada tutma ve otorite kurma görevlerinde değerlendirilebilir."],
  "Vartolu Saadettin":["merchant","Pazarlık, fırsat ve beklenmedik yöntemleri birleştiren bir tercih."],
  "Cumali Koçovalı":["protector","Doğrudan müdahale ve kararlılık gerektiren saha görevleri için düşün."],
  "Sena Koçovalı":["rebel","Baskı altında kendi yolunu arayan, farklı bakış getiren bir tercih."],
  "Selim Koçovalı":["observer","İç dengeleri ve kişisel motivasyonları okuma rolünde değerlendirilebilir."],
  "Kuzey Tekinoğlu":["rebel","Cesaret ve hızlı aksiyon isteyen görevlerde güçlü ama riskli bir tercih."],
  "Güney Tekinoğlu":["strategist","Hedefe adım adım ilerleme ve konum kazanma rolüne aday."],
  "Cemre Çayak":["diplomat","Yakın ilişkileri ve değişen koşulları yönetme görevlerinde düşünülebilir."],
  "Banu Sinaner":["merchant","Kaynak ve sosyal çevre avantajını kullanma rolünde değerlendirilebilir."],
  "Ali Vefa":["healer","Analitik düşünme ve sağlık odaklı çözüm gerektiren görevlerde değerlendirilebilir."],
  "Ferman Eryiğit":["healer","Uzmanlık ile ekip koordinasyonunu birleştiren destek rolüne aday."],
  "Bahar Özden":["healer","Dayanışma, öğrenme ve toparlanma odaklı bir kadroya destek sunabilir."],
  "Timur Yavuzoğlu":["healer","Uzmanlık isteyen görevlerde kullanılabilecek, uyumu ayrıca düşünülmesi gereken bir tercih."],
  "Sarp Yılmaz":["protector","Zor koşullarda saha kararı ve takip gerektiren görevlerde düşünülebilir."],
  "Mert Karadağ":["observer","Gizli bilgi ve farklı tarafları izleme üzerine kurulacak bir tercih."],
  "Celal Duman":["leader","İnsan ve kaynak ilişkilerini kontrol etme rolünde etkili ama baskın bir tercih."],
  "Melek Yıldız":["diplomat","Farklı taraflar arasında ilişki kurma ve gerilimi okuma rolü için düşün."],
  "Seyit Eminof":["protector","Disiplin ve riskli koşullarda kararlılık gerektiren görevlerde düşünülebilir."],
  "Şura":["diplomat","Yeni koşullara uyum ve insan ilişkileri odaklı bir role aday."],
  "Azize":["strategist","Geçmiş bilgiyi ve uzun vadeli planları kullanma rolünde değerlendirilebilir."],
  "Miran Aslanbey":["rebel","Güçlü motivasyonla harekete geçme rolünde etkili, duygusal riskleri olan bir tercih."],
  "Reyyan Şadoğlu":["diplomat","Çatışan ilişkiler arasında dayanışma kurma rolüne aday."],
  "Alya Albora":["healer","Bakım, dayanıklılık ve zor koşullarda toparlanma rolünde düşünülebilir."],
  "Cihan Albora":["leader","Aile ve çevre sorumluluğunu üstlenen yönetim rolüne aday."],
  "Ferit Korhan":["rebel","Sosyal çevre ve ani kararların önemli olduğu görevlerde düşünülebilir."],
  "Seyran Şanlı":["artist","Kendi yolunu bulma ve yaratıcı çözüm arama rolünde değerlendirilebilir."],
  "Kazım Şanlı":["merchant","Çıkar ve pazarlık odaklı görevlerde kullanılabilecek sert bir tercih."],
  "Halis Ağa":["leader","Yerleşik düzen ve otorite üzerine kurulacak bir yönetici tercihi."],
};
export function getCharacterProfile(character: CharacterSeed): CharacterProfile | null {
  const canonical=canonicalCharacter("Türk Dizi Evreni",character);
  if(!canonical || canonical.source!==character.source) return null;
  const entry=PROFILES[canonical.name]; if(!entry)return null;
  return {...ROLES[entry[0]], description:entry[1]};
}
